sonar.projectKey=sleepadvisor
sonar.projectName=SleepAdvisor
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/migrations/**,**/var/**,**/vendor/**,**/public/**
sonar.test.exclusions=tests/**

# Règles courantes — dette technique
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
